name = "roblox"
version = "0.1.0"
target = "luau"

[luau]
runtime = "roblox"

[dependencies]
gleam_json = ">= 3.1.0 and < 4.0.0"
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
gleam_fetch = ">= 1.4.0 and < 2.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"
simplifile = ">= 2.4.0 and < 3.0.0"
gleam_javascript = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"

[javascript]
runtime = "nodejs"
