// Generated enum item bindings for Roblox API
import roblox/enum.{type RobloxEnum}
import roblox/types.{type PathStatus}

@target(luau)
/// The success of a Path generated by PathfindingService.
///
/// Roblox: `Enum.PathStatus`
/// See: https://create.roblox.com/docs/reference/engine/enums/PathStatus
@luau.global("Enum.PathStatus")
pub fn roblox_enum() -> RobloxEnum(PathStatus)

@target(luau)
/// Roblox enum item `PathStatus.Success`.
@luau.global("Enum.PathStatus.Success")
pub fn success() -> PathStatus

@target(luau)
/// Roblox enum item `PathStatus.ClosestNoPath`.
@luau.global("Enum.PathStatus.ClosestNoPath")
pub fn closest_no_path() -> PathStatus

@target(luau)
/// Roblox enum item `PathStatus.ClosestOutOfRange`.
@luau.global("Enum.PathStatus.ClosestOutOfRange")
pub fn closest_out_of_range() -> PathStatus

@target(luau)
/// Roblox enum item `PathStatus.FailStartNotEmpty`.
@luau.global("Enum.PathStatus.FailStartNotEmpty")
pub fn fail_start_not_empty() -> PathStatus

@target(luau)
/// Roblox enum item `PathStatus.FailFinishNotEmpty`.
@luau.global("Enum.PathStatus.FailFinishNotEmpty")
pub fn fail_finish_not_empty() -> PathStatus

@target(luau)
/// Roblox enum item `PathStatus.NoPath`.
@luau.global("Enum.PathStatus.NoPath")
pub fn no_path() -> PathStatus

/// Keeps Roblox imports reachable when checking non-Luau targets.
pub fn javascript_type_anchor(_: RobloxEnum(PathStatus), _: PathStatus) -> Nil {
  Nil
}
